
- name: update apt
  shell: apt-get update
  sudo: yes
  tags:
    - config

- name: add nginx repository
  copy: src=apt-sources.list dest=/etc/apt/sources.list
              owner=root group=root mode=0644
  sudo: yes
  tags:
    - config

- name: create webapps directory
  shell: mkdir ~/webapps; exit 0 
  tags:
    - config

- name: install nginx
  apt: name=nginx state=installed force=yes
  sudo: yes
  tags:
    - config

- name: install htop
  apt: name=htop state=installed
  sudo: yes
  tags:
    - config

- name: set default nginx site
  copy: src=default-nginx-site dest=/etc/nginx/sites-available/default
              owner=root group=root mode=0644
  sudo: yes
  tags:
    - config

- name: install jetty
  apt: name=jetty8 state=installed
  sudo: yes
  tags:
    - config

# TODO remove this once a real DB is used. for now, we just give 777 permissions to allow DB file to be created at Boot
- name: give write permissions to everybody 
  command: chmod 777 /usr/share/jetty8/
  sudo: yes
  tags:
    - config

- name: install jetty8 default file
  copy: src=jetty8 dest=/etc/default/jetty8
              owner=root group=root mode=0644
  sudo: yes
  tags:
    - config

- name: install postgres
  apt: name=postgresql-9.1 state=installed
  sudo: yes
  tags:
    - config

- name: create database helloworld
  shell: psql --dbname=postgres --command="CREATE DATABASE helloworld;"; exit 0;
  sudo: yes
  sudo_user: postgres
  tags:
   - config

- name: create user webapp
  shell: psql --dbname=postgres --command="CREATE USER webapp WITH PASSWORD 'webapp'"; exit 0;
  sudo: yes
  sudo_user: postgres
  tags:
   - config

- name: grant connect on helloworld to webapp user
  shell: psql --dbname=postgres --command="GRANT CONNECT ON DATABASE helloworld TO webapp;"; exit 0;
  sudo: yes
  sudo_user: postgres
  tags:
   - config

- name: test database connection for webapp user
  shell: export PGPASSWORD='webapp'; psql --dbname=helloworld --user=webapp --host=127.0.0.1 --command="SELECT 'test me'";
  sudo: yes
  sudo_user: postgres
  tags:
   - config

- name: grant usage on helloworld.public to user webapp
  shell: psql --dbname=helloworld --command="GRANT USAGE ON SCHEMA public TO webapp;"
  sudo: yes
  sudo_user: postgres
  tags:
   - config

- name: reboot vm
  shell: reboot
  sudo: yes
  tags:
    - config





























