
- name: copy {{site_name}} app
  local_action: command rsync --delete -a helloworld/target/{{site_name}}-1.0-SNAPSHOT {{inventory_hostname}}:~/webapps/ 
  tags:
    - deploy

- name: install {{site_name}} app
  shell: rm -rf /usr/share/jetty8/webapps/{{site_name}} && cp -r /home/yorrick/webapps/{{site_name}}-1.0-SNAPSHOT /usr/share/jetty8/webapps/{{site_name}}
  sudo: yes
  tags:
    - deploy

- name: install nginx site file
  template: src=nginx-config dest=/etc/nginx/sites-available/{{site_name}}
  sudo: yes
  tags:
    - deploy

- name: link nginx site file
  file: path=/etc/nginx/sites-enabled/{{site_name}} src=/etc/nginx/sites-available/{{site_name}} state=link
  sudo: yes
  tags:
    - deploy    
