
- name: install {{site_name}} app war file
  copy: src={{site_name}}-1.0-SNAPSHOT.war dest=/usr/share/jetty8/webapps/{{site_name}}.war
  sudo: yes
  tags:
    - deploy

- name: install {{site_name}} app context file
  template: src=war-context.xml dest=/usr/share/jetty8/contexts/
  sudo: yes
  tags:
    - deploy

- name: install nginx site file
  template: src=nginx-config dest=/etc/nginx/sites-available/{{site_name}}
  sudo: yes
  tags:
    - deploy

- name: link nginx site file
  file: path=/etc/nginx/sites-enabled/{{site_name}} src=/etc/nginx/sites-available/{{site_name}} state=link
  sudo: yes
  tags:
    - deploy    
