
- name: update apt
  shell: apt-get update
  sudo: yes
  tags:
    - config

- name: add nginx repository
  copy: src=apt-sources.list dest=/etc/apt/sources.list
              owner=root group=root mode=0644
  sudo: yes
  tags:
    - config

- name: install nginx
  apt: name=nginx state=installed force=yes
  sudo: yes
  tags:
    - config

- name: remove default nginx site
  shell: rm /etc/nginx/sites-enabled/default
  sudo: yes
  tags:
    - config

- name: install jetty
  apt: name=jetty8 state=installed
  sudo: yes
  tags:
    - config

- name: install jetty8 default file
  copy: src=jetty8 dest=/etc/default/jetty8
              owner=root group=root mode=0644
  sudo: yes
  tags:
    - config

- name: reboot vm
  shell: reboot
  sudo: yes
  tags:
    - config

- name: install nginx site file
  copy: src=nginx-helloworld dest=/etc/nginx/sites-available/helloworld
  sudo: yes
  tags:
    - deploy

- name: link nginx site file
  file: path=/etc/nginx/sites-enabled/helloworld src=/etc/nginx/sites-available/helloworld state=link
  sudo: yes
  tags:
    - deploy    

- name: install helloworld app war file
  copy: src=helloworld-1.0-SNAPSHOT.war dest=/usr/share/jetty8/webapps/helloworld.war
  sudo: yes
  tags:
    - deploy

- name: install helloworld app context file
  copy: src=helloworld.xml dest=/usr/share/jetty8/contexts/
  sudo: yes
  tags:
    - deploy

- name: reload jetty
  service: name=jetty8 state=restarted
  sudo: yes
  tags:
    - deploy

- name: reload nginx
  service: name=nginx state=reloaded
  sudo: yes
  tags:
    - deploy

- name: test root url from local
  shell: 'wget -O - --header="Host: localhost.helloworld.com" localhost'
  tags:
    - test-deploy

