# We could as well set up a maintenance page in nginx during jetty reboot

- name: stop nginx
  service: name=nginx state=stopped
  sudo: yes
  tags:
    - deploy

- name: reload jetty
  service: name=jetty8 state=restarted
  sudo: yes
  tags:
    - deploy

- name: start nginx
  service: name=nginx state=started
  sudo: yes
  tags:
    - deploy
