
- name: test jetty url
  shell: 'wget -O - --header="Host:{{item}}" localhost:10000/'
  with_items: site_names
  tags:
    - deploy
    - test

- name: test nginx url
  shell: 'wget -O - --header="Host:{{item}}.localhost.com" localhost'
  with_items: site_names
  tags:
    - deploy   
    - test

- name: test url from host
  local_action: shell wget -O - --header="Host:{{item}}.localhost.com" {{inventory_hostname}}
  with_items: site_names
  tags:
    - deploy   
    - test

- name: test url from host for static ressources
  local_action: shell wget -O /dev/null --header="Host:{{item}}.localhost.com" {{inventory_hostname}}/images/kitten.jpeg
  with_items: site_names
  tags:
    - deploy   
    - test

